Revert "Change chart.Version to release version."
This reverts commit 44076f6b

diff --git a/install/helm/gloo/templates/5-resource-rollout-check-job.yaml b/install/helm/gloo/templates/5-resource-rollout-check-job.yaml
--- a/install/helm/gloo/templates/5-resource-rollout-check-job.yaml
+++ b/install/helm/gloo/templates/5-resource-rollout-check-job.yaml
@@ -97,27 +97,11 @@ spec:
                     echo "Rollout job failed. Not all resources were successfully created."
                     exit 1
                 fi
-                
-                # Add retry mechanism in case gloo-resource-rollout has not started yet.
-                no_of_attempts=20
-                i=0
-                until [ $i -eq $no_of_attempts ]
-                  sleep 5
-                  echo "Iteration $i..."
-                  i=$((i+1))
-            
-                  kubectl -n {{ .Release.Namespace }} get job gloo-resource-rollout &> /dev/null
-                  
-                  if [ $? -eq 0 ]
-                    echo "Waiting for the resource rollout job to complete"
-                    kubectl -n {{ .Release.Namespace }} wait --for=condition=complete job gloo-resource-rollout --timeout={{ .Values.gateway.rolloutJob.timeout }}s || exit 1
-    
-                    # Clean up the rollout job up so it doesn't cause issues with upgrades
-                    kubectl -n {{ .Release.Namespace }} delete job gloo-resource-rollout || exit $?
-            
-                    break
-                  fi
-                done
+                echo "Waiting for the resource rollout job to complete"
+                kubectl -n {{ .Release.Namespace }} wait --for=condition=complete job gloo-resource-rollout --timeout={{ .Values.gateway.rolloutJob.timeout }}s || exit 1
+
+                # Clean up the rollout job up so it doesn't cause issues with upgrades
+                # kubectl -n {{ .Release.Namespace }} delete job gloo-resource-rollout
               fi
 
               # If the resource has been applied, re-applying it should output something like this
